### ISSUE TITLE
Can not use transportSecurity-1.0 in ICN docker image

### ISSUE THREAD

**Issue by benzman81** [ibm-ecm/container-samples#8]
We use the ICN docker image and deploy it to kubernetes cluster using mostly the default configs from this repository. As we want to use outbound ssl connection from our icn plugin we need to use the server feature "transportSecurity-1.0". But if we activate and configure it throws the following error:

`Caused by: java.lang.RuntimeException: com.ibm.ws.ssl.protocol.LibertySSLSocketFactory
	at com.ibm.ws.kernel.boot.security.SSLSocketFactoryProxy.<init>(SSLSocketFactoryProxy.java:38)
	at java.lang.J9VMInternals.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1848)
	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:31)
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:16)
	at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:27)
	at com.ibm.net.ssl.www2.protocol.https.b.<init>(b.java:11)
	at com.ibm.net.ssl.www2.protocol.https.Handler.openConnection(Handler.java:1)
	at com.ibm.net.ssl.www2.protocol.https.Handler.openConnection(Handler.java:4)
	at java.net.URL.openConnection(URL.java:991)`

Digging a bit deeper it looks like this is a class not found exception.

Using the same configuration in a sample app on websphere liberty docker image works like a charm. If I add this sample app to the ICN docker image server I get the same exception.

Any ideas?

Regards,
Markus

**Comment by Vincent-Le** [comment]
@benzman81 - if you are still seeing this issue, can you open a support ticket with IBM so that we can get the details of your deployment?

**Comment by jekahn** [comment]
Closing this issue as no activity in 60 days.
